#pragma once

#define IDS_EXPLORE                     103
#define IDS_OPEN                        104
#define IDS_GROUPBYSIDES                105
#define IDS_EXPLORE_HELP                106
#define IDS_OPEN_HELP                   107
#define IDS_ONE                         108
#define IDS_TWO                         109
#define IDS_THREE                       110
#define IDS_FOUR                        111
#define IDS_FIVE                        112
#define IDS_SIX                         113
#define IDS_SEVEN                       114
#define IDS_EIGHT                       115
#define IDS_NINE                        116
#define IDS_ZERO                        117
#define IDS_GROUPBYSIZE                 118
#define IDS_GROUPBYALPHA                119
#define IDS_VALUE                       120
#define IDS_SMALL                       121
#define IDS_MEDIUM                      122
#define IDS_LARGE                       123
#define IDS_LESSTHAN5                   124
#define IDS_5ORGREATER                  125
#define IDS_GROUPBYVALUE                126
#define IDS_GROUPBYLEVEL                127
#define IDS_RECTANGLE                   128
#define IDS_TRIANGLE                    129
#define IDS_CIRCLE                      130
#define IDS_POLYGON                     131
#define IDS_STRING132                   132
#define IDS_TITLE                       132
#define IDS_DISPLAY                     133
#define IDS_UNSPECIFIED                 134
#define IDS_SETTINGS                    135
#define IDS_SETTING1                    136
#define IDS_SETTING2                    137
#define IDS_SETTING3                    138
#define IDS_DISPLAY_TT                  139
#define IDS_SETTINGS_TT                 140
#define IDS_SETTING1_TT                 141
#define IDS_SETTING2_TT                 142
#define IDS_SETTING3_TT                 143

#define IDD_NAMEBOX                     4001
#define IDD_PERMBOX                     4000

#define IDD_PERMPAGE                     4002

#define IDD_SITEPAGE                     4003
#define IDD_SITEBOX                      4004
#define IDD_COPYBOX                      4007

#define IDC_COPY_SOURCE_LABEL             4101
#define IDC_COPY_SOURCE                   4102
#define IDC_COPY_ORIGINAL                 4103
#define IDC_COPY_SAME_SITE                4104
#define IDC_COPY_OTHER_SITE               4105
#define IDC_COPY_LOCAL                    4106
#define IDC_COPY_SITE_LABEL               4107
#define IDC_COPY_SITE                     4108
#define IDC_COPY_PATH_LABEL               4109
#define IDC_COPY_PATH                     4110
#define IDC_COPY_BROWSE                   4111
#define IDC_COPY_DESTINATION              4112
#define IDC_PROP_NAME                    3030
#define IDC_PROP_TYPE                    3031
#define IDC_PROP_PERMISSIONS             3032
#define IDC_PROP_OWNER                   3033
#define IDC_PROP_GROUP                   3034
#define IDC_PROP_SIZE                    3035
#define IDC_PROP_MODIFIED                3036
#define IDC_PROP_PERMISSION_GROUP        3037
#define IDC_PROP_OWNER_ROLE              3038
#define IDC_PROP_GROUP_ROLE              3039
#define IDC_PROP_OTHERS_ROLE             3040
#define IDC_PROP_OCTAL_LABEL             3041
#define IDC_SITE_NAME_LABEL              4011
#define IDC_SITE_HOST_LABEL              4012
#define IDC_SITE_PROTOCOL_LABEL          4013
#define IDC_SITE_PORT_LABEL              4014
#define IDC_SITE_USER_LABEL              4015
#define IDC_SITE_START_PATH_LABEL        4016
